<?php foreach ($flash as $messages) : ?>
    <?php foreach ($messages as $message) : ?>
        <p>
            <?= $message ?>
        </p>
    <?php endforeach ?>
<?php endforeach ?>

<?php if (isset($activeUser['id'])) : ?>
    <div>Привет, <?= $activeUser['name'] ?>!</div>
    <form action="/logout" method="post">
        <div>
            <input type="submit" value="Log out">
        </div>
    </form>
<?php endif ?>

<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<div>
    <a href="/users/new">Создать нового пользователя</a>
</div>

<div>
    <a href="/login">Войти</a>
</div>

<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['name']) ?></a></td>
            <td><?= htmlspecialchars($user['email']) ?></td>
        </tr>
    <?php endforeach ?>
</table>
